// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	runtimeFieldNames          = builder.RawFieldNames(&Runtime{}, true)
	runtimeRows                = strings.Join(runtimeFieldNames, ",")
	runtimeRowsExpectAutoSet   = strings.Join(stringx.Remove(runtimeFieldNames, "id"), ",")
	runtimeRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(runtimeFieldNames, "id"))
)

type (
	runtimeModel interface {
		Insert(ctx context.Context, data *Runtime) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Runtime, error)
		FindOneByRuntimeId(ctx context.Context, runtimeId string) (*Runtime, error)
		Update(ctx context.Context, data *Runtime) error
		Delete(ctx context.Context, id int64) error
	}

	defaultRuntimeModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Runtime struct {
		Id        int64     `db:"id"`
		RuntimeId string    `db:"runtime_id"`
		Name      string    `db:"name"`
		Status    int64     `db:"status"`
		CreatedAt time.Time `db:"created_at"`
		UpdatedAt time.Time `db:"updated_at"`
	}
)

func newRuntimeModel(conn sqlx.SqlConn) *defaultRuntimeModel {
	return &defaultRuntimeModel{
		conn:  conn,
		table: `"public"."runtime"`,
	}
}

func (m *defaultRuntimeModel) withSession(session sqlx.Session) *defaultRuntimeModel {
	return &defaultRuntimeModel{
		conn:  sqlx.NewSqlConnFromSession(session),
		table: `"public"."runtime"`,
	}
}

func (m *defaultRuntimeModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultRuntimeModel) FindOne(ctx context.Context, id int64) (*Runtime, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", runtimeRows, m.table)
	var resp Runtime
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRuntimeModel) FindOneByRuntimeId(ctx context.Context, runtimeId string) (*Runtime, error) {
	var resp Runtime
	query := fmt.Sprintf("select %s from %s where runtime_id = $1 limit 1", runtimeRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, runtimeId)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRuntimeModel) Insert(ctx context.Context, data *Runtime) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5)", m.table, runtimeRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.RuntimeId, data.Name, data.Status, data.CreatedAt, data.UpdatedAt)
	return ret, err
}

func (m *defaultRuntimeModel) Update(ctx context.Context, newData *Runtime) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, runtimeRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.RuntimeId, newData.Name, newData.Status, newData.CreatedAt, newData.UpdatedAt)
	return err
}

func (m *defaultRuntimeModel) tableName() string {
	return m.table
}
