// Code generated by goctl. DO NOT EDIT.
// Source: job.proto

package server

import (
	"context"

	"oasisscan-backend/job/internal/logic"
	"oasisscan-backend/job/internal/svc"
	"oasisscan-backend/job/proto"
)

type JobServer struct {
	svcCtx *svc.ServiceContext
	proto.UnimplementedJobServer
}

func NewJobServer(svcCtx *svc.ServiceContext) *JobServer {
	return &JobServer{
		svcCtx: svcCtx,
	}
}

func (s *JobServer) ScanHeight(ctx context.Context, in *proto.ScanHeightRequest) (*proto.ScanHeightResponse, error) {
	l := logic.NewScanHeightLogic(ctx, s.svcCtx)
	return l.ScanHeight(in)
}
