# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Testnet

on:
  push:
    branches: [ "testnet" ]
  pull_request:
    branches: [ "testnet" ]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /mnt/oasisscan-backend/
            git checkout testnet
            git pull origin testnet
            PATH="/usr/local/go/bin/:$PATH"
            sh /mnt/backend-job/deploy_testnet.sh
            sh /mnt/backend-api/deploy_testnet.sh

      - name: Deploy to Backup
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.BACKUP_SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /mnt/oasisscan-backend/
            git checkout testnet
            git pull origin testnet
            PATH="/usr/local/go/bin/:$PATH"
            sh /mnt/backend-job/deploy_testnet.sh
            sh /mnt/backend-api/deploy_testnet.sh